-- Importa as 23 FAQs padrão do site (espelha src/lib/faqs.ts)
-- Executar no Supabase: SQL Editor → New query → Run
-- Seguro reexecutar: só insere se a pergunta ainda não existir.

INSERT INTO faqs (category, question, answer, display_order, published)
SELECT v.category, v.question, v.answer, v.display_order, true
FROM (VALUES
  ('Consulta e Agendamento', 'Quais condições a Dra. Janaína trata?', 'Atendo todas as condições ortopédicas gerais (ombro, joelho, quadril, coluna) com subespecialidade em cirurgia da mão e punho — incluindo síndrome do túnel do carpo, dedo em gatilho, rizartrose, fraturas de punho e escafóide, cisto sinovial e tendinite de De Quervain.', 0),
  ('Consulta e Agendamento', 'Como funciona a primeira consulta?', 'Na primeira consulta faço uma avaliação completa: escuto sua história, examino a região afetada e analiso exames que você já tenha. Se necessário, solicito exames complementares. Ao final, explico o diagnóstico e as opções de tratamento de forma clara.', 1),
  ('Consulta e Agendamento', 'Preciso de encaminhamento para consultar?', 'Não. Você pode agendar diretamente comigo, sem necessidade de encaminhamento, tanto para consultas particulares quanto por convênio.', 2),
  ('Consulta e Agendamento', 'Quais exames devo levar na consulta?', 'Traga todos os exames que já tenha: raio-X, ressonância magnética, ultrassom, exames de sangue recentes e lista de medicamentos em uso. Isso agiliza o diagnóstico e evita exames desnecessários.', 3),
  ('Consulta e Agendamento', 'Qual o endereço do consultório?', 'O consultório fica em Belo Horizonte, MG. Entre em contato pelo WhatsApp ou telefone para obter o endereço completo e informações sobre estacionamento.', 4),
  ('Consulta e Agendamento', 'Quanto tempo dura uma consulta?', 'A primeira consulta costuma durar entre 30 e 45 minutos, pois faço uma avaliação completa. Retornos são mais rápidos, entre 15 e 20 minutos, dependendo da complexidade do caso.', 5),
  ('Condições da Mão e Punho', 'O que é o túnel do carpo?', 'A síndrome do túnel do carpo é a compressão do nervo mediano no punho. Causa dormência nos dedos (principalmente à noite), formigamento, perda de força e dor. É muito comum e pode ser tratada de forma conservadora ou cirúrgica, dependendo da gravidade.', 6),
  ('Condições da Mão e Punho', 'Síndrome do túnel do carpo tem cura?', 'Na maioria dos casos, o tratamento adequado permite resolução ou melhora significativa dos sintomas. Nos casos leves, o uso de órtese noturna e fisioterapia podem trazer alívio. Nos casos moderados a graves, a cirurgia de liberação do túnel do carpo tem taxa de sucesso superior a 90% segundo a literatura médica. Resultados individuais podem variar.', 7),
  ('Condições da Mão e Punho', 'O que é dedo em gatilho?', 'É uma condição em que o dedo trava ao dobrar, causada pela inflamação da polia A1 na base do dedo. É mais comum em mulheres, diabéticos e pessoas que fazem atividades repetitivas com as mãos.', 8),
  ('Condições da Mão e Punho', 'Meu dedo trava ao dobrar. É grave?', 'O dedo em gatilho não é grave, mas tende a piorar sem tratamento. Nos estágios iniciais, infiltração com corticoide tem bons resultados na literatura (67-90% dos casos). Quando há travamento persistente, a cirurgia é um procedimento rápido e bem estabelecido, com alta taxa de sucesso. Cada caso é avaliado individualmente.', 9),
  ('Condições da Mão e Punho', 'O que é rizartrose?', 'Rizartrose é a artrose na base do polegar. Causa dor ao abrir garrafas, girar chaves e segurar objetos. Afeta principalmente mulheres após os 40 anos. O tratamento vai de órtese e fisioterapia até cirurgia nos casos avançados.', 10),
  ('Condições da Mão e Punho', 'Formigamento na mão de noite é normal?', 'Não. Formigamento noturno recorrente — especialmente no polegar, indicador e médio — é o sintoma mais clássico da síndrome do túnel do carpo. Se acontece mais de 3 vezes por semana ou está piorando, procure avaliação.', 11),
  ('Cirurgias e Procedimentos', 'A Dra. Janaína realiza cirurgias?', 'Sim. Tenho formação em cirurgia da mão e punho, com pós-graduação pela Faculdade Ciências Médicas de Minas Gerais (FCMMG). Realizo desde procedimentos ambulatoriais simples, como liberação de dedo em gatilho (20 min com anestesia local), até cirurgias mais complexas como descompressão do túnel do carpo e fraturas.', 12),
  ('Cirurgias e Procedimentos', 'A cirurgia de túnel do carpo é perigosa?', 'Não. É um procedimento seguro, bem estabelecido e com alta taxa de sucesso (acima de 90%). Pode ser feita com anestesia local ou regional, dura de 15 a 30 minutos e o paciente vai para casa no mesmo dia.', 13),
  ('Cirurgias e Procedimentos', 'Posso tratar sem cirurgia?', 'Sempre que possível, priorizo o tratamento conservador: fisioterapia, órteses, anti-inflamatórios e infiltrações. A cirurgia é indicada quando o tratamento conservador não trouxe melhora adequada ou quando há comprometimento grave.', 14),
  ('Cirurgias e Procedimentos', 'A cirurgia de mão pelo plano de saúde é possível?', 'Sim. A maioria dos procedimentos de cirurgia da mão é coberta pelos planos de saúde, incluindo túnel do carpo, dedo em gatilho e fraturas. Consulte seu convênio para confirmar a cobertura.', 15),
  ('Recuperação', 'Quanto tempo dura a recuperação de uma cirurgia de mão?', 'Depende do procedimento. Cirurgias simples como dedo em gatilho permitem retorno às atividades leves em poucos dias. Cirurgias mais complexas como túnel do carpo podem levar 2-4 semanas para recuperação funcional. Cada caso é avaliado individualmente.', 16),
  ('Recuperação', 'Quanto tempo fico de gesso no punho?', 'Depende do tipo de fratura. Fraturas simples do rádio distal levam 4-6 semanas de imobilização. Fraturas de escafoide podem exigir 8-12 semanas. Quando a fixação é cirúrgica, o tempo de gesso é geralmente menor.', 17),
  ('Recuperação', 'Posso dirigir após uma cirurgia de mão?', 'Geralmente o retorno à direção leva de 2 a 4 semanas após cirurgias simples (dedo em gatilho, túnel do carpo). Fraturas e procedimentos mais complexos podem exigir mais tempo. Oriento individualmente cada paciente.', 18),
  ('Recuperação', 'Preciso de fisioterapia após a cirurgia?', 'Na maioria das cirurgias da mão, a reabilitação é parte fundamental do resultado. Dependendo do procedimento, a fisioterapia pode começar dias após a cirurgia para evitar rigidez e recuperar a função o mais rápido possível.', 19),
  ('Convênios e Valores', 'Quais convênios a Dra. Janaína atende?', 'Atendo consultas particulares e por convênios. Entre em contato pelo WhatsApp para verificar se seu plano de saúde é aceito e obter informações sobre disponibilidade de agenda.', 20),
  ('Convênios e Valores', 'Quanto custa uma consulta particular?', 'O valor da consulta particular é informado no momento do agendamento. Entre em contato pelo WhatsApp para obter informações atualizadas sobre valores e formas de pagamento.', 21),
  ('Convênios e Valores', 'Atende urgências e emergências?', 'Meu consultório é voltado para atendimento eletivo (consultas agendadas). Em caso de emergência ortopédica (fratura exposta, luxação, lesão grave), procure o pronto-socorro mais próximo. Após o atendimento inicial, posso acompanhar seu caso no consultório.', 22)
) AS v(category, question, answer, display_order)
WHERE NOT EXISTS (
  SELECT 1 FROM faqs f WHERE f.question = v.question
);
